server:
  port: 9200
spring:
  application:
    name: gateway-eureka-demo
  redis:
      host: 127.0.0.1
      port: 6379
  # 添加security安全认证
  #security:
  # user:
  #    name: Kevin
  #    password: Kevin

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            exposedHeaders:
            - content-type
            allowedHeaders:
            - content-type
            allowCredentials: true
            allowedMethods:
            - GET
            - OPTIONS
            - PUT
            - DELETE
            - POST
      routes:
#      - id: path_route_1
#        uri: http://www.baidu.com
#        predicates:
#        - Path=/*
      - id: path_route_2
        uri: http://www.baidu.com
        predicates:
        - Path=/
      - id: user-service
        # 以 lb:// 开头，代表从注册中心 获取服务。
        uri: lb://eureka-client-user-service
        predicates:
        - Path=/user-service/**
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            key-resolver: "#{@ipKeyResolver}"
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      # 配置 Eureka 的支持
      discovery:
        locator:
          # 开启支持 , 启用基于服务发现的路由定位
          enabled: true
          # 配置通过 小写的 服务名可以进行访问
          # http://网关地址/服务名称（小写）/**
          lower-case-service-id: true
# 将服务注册到 Eureka服务中心
eureka:
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    client:
      service-url:
        defaultZone: http://kevin:Kevin@localhost:8761/eureka/

#开放所有页面节点  默认只开启了health、info两个节点
management:
  endpoints:
    web:
      exposure:
        include: "*"

